version: '3.1'

services:
  rethinkdb:
    image: rethinkdb
  api:
    build: ./api
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: rethinkdb
      DOCKER: true
secrets:
  discord_application:
    file: ./secrets/discord_application.json
