version: '3.1'

services:
  rethinkdb:
    image: rethinkdb
    ports:
      - 127.0.0.1:9000:8080
  api:
    build: ./api
    ports:
      - 8000:8000
    environment:
      DATABASE_HOST: rethinkdb
secrets:
  discord_application:
    file: ./secrets/discord_application.json
environment:
  DOCKER: true
